### ISSUE TITLE
[Feat / Controller]  Channel-admin 컨트롤러 구현 

### ISSUE THREAD

**Issue by ManOfDemosan** [Dr-Pong/dr_pong_chat_server#112]
## Desc

Channel -admin관련 테스트 코드 작성

## Todo
- [x] PATCH /channels/{roomId}
- [x] DELETE /channels/{roomId}
- [x] POST /channels/{roomId}/admin/{nickname}
- [x] DELETE /channels/{roomId}/admin/{nickname}
- [x] POST /channels/{roomId}/ban/{nickname}
- [x] POST /channels/{roomId}/kick/{nickname}
- [x] POST /channels/{roomId}/mute/{nickname}
- [x] DELETE /channels/{roomId}/mute/{nickname}
