### ISSUE TITLE
[refactor] friend 도메인 테스트 서비스 리팩토링 

### ISSUE THREAD

**Issue by triplecheeseburger** [Dr-Pong/dr_pong_chat_server#118]
## Desc

테스트 서비스를 리팩토링합니다.
## Detail

쓰기 좀 더 편하게 바꿔보아요. 겹치는 부분은 분리해보아요.
## Todo
- [ ] friend.test.service
- [ ] direct-message.test.service
- [ ] direct-message-room.test.service
