### ISSUE TITLE
[Test / Controller] Channel Normal 테스트코드 작성

### ISSUE THREAD

**Issue by nheo9143** [Dr-Pong/dr_pong_chat_server#134]
## Desc

- 일반 유저용 채널 컨트롤러 테스트 작성
## Todo
- [x] GET /channels?page={page}&count={count}&order={'recent' | 'popular'}&keyword={keyword | null}
- [x] GET /channels/{roomId}/participants
- [x] POST /channels
- [x] POST /channels/{roomId}/participants
- [x] DELETE /channels/{roomId}/participants
- [x] POST /channels/{roomId}/invitation/{nickname}
- [x] POST /channels/{roomId}/magicpass
- [x] POST /channels/{roomId}/chats
- [x] GET /channels/me
- [x] GET /channels/{roomId}chats?offset={offset}&count={count}
