### ISSUE TITLE
[Fix/ Test / Controller] 유저 이미지 변경건

### ISSUE THREAD

**Issue by ManOfDemosan** [Dr-Pong/dr_pong_chat_server#158]
## Desc

유저 이미지 jwt 가드 설정 
## Todo
- [ ] 유저 컨트롤러 jwt가드설정
- [ ] 유저 서비스 테스트파일
- [ ] 유저 컨트롤러 테스트파일
