### ISSUE TITLE
[Feat] Jenkinis CI/CD add 

### ISSUE THREAD

**Issue by maindishes** [Dr-Pong/dr_pong_chat_server#243]
## Desc

jenkins ci/cd 추가 
## Detail

정리글은 notion 이나 velog에 따로 이쁘게 정리할 예정 
## Todo
- [ ] jenkins item 만들기  
- [ ] npm test 하는것도 추가하기 
- [ ] ec2 에 deploy 확인하기
