### ISSUE TITLE
[Feat / Controller] friend 도메인 컨트롤러 껍데기 만들기

### ISSUE THREAD

**Issue by triplecheeseburger** [Dr-Pong/dr_pong_chat_server#40]
## Desc

friend 도메인 컨트롤러 껍데기 만들기

## Todo
- [x] 친구 목록 조회
- [x] 친구 요청
- [x] 친구 요청 목록 조회 (pending list)
- [x] 친구 요청 수락
- [x] 친구 요청 거절
- [x] 친구 삭제
- [x] DM 대화 내역
- [x] DM 전송
- [x] 진행 중인 DM 목록 받기
- [x] 진행 중인 DM 리스트에서 특정 방 삭제
- [x] 새로운 DM 유무 확인
