### ISSUE TITLE
[Test / Controller] friend 컨트롤러 테스트

### ISSUE THREAD

**Issue by triplecheeseburger** [Dr-Pong/dr_pong_chat_server#42]
## Desc

friend 컨트롤러 테스트

## Todo
- [ ]  친구 목록 조회
- [ ]  친구 요청
- [ ]  친구 요청 목록 조회 (pending list)
- [ ]  친구 요청 수락
- [ ]  친구 요청 거절
- [ ]  친구 삭제
- [ ]  DM 대화 내역
- [ ]  DM 전송
- [ ]  진행 중인 DM 목록 받기
- [ ]  진행 중인 DM 리스트에서 특정 방 삭제
- [ ]  새로운 DM 유무 확인
